### ISSUE TITLE
Set up sass-lint

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#313]
- Add `.sass-lint.yml`
- Add sass-lint to CI

```
# sass-lint config generated by make-sass-lint-config v0.2.2
#
# The following scss-lint Linters are not yet supported by sass-lint:
# ChainedClasses, DisableLinterReason, ElsePlacement, PrivateNamingConvention
# PropertyCount, PseudoElement, SelectorDepth, SpaceAfterComment
# SpaceAfterVariableColon, SpaceAroundOperator, TrailingWhitespace, UnnecessaryParentReference
# Compass::*
#
# The following settings/values are unsupported by sass-lint:
# Linter Comment, option "style"
# Linter Indentation, option "allow_non_nested_indentation"
# Linter Indentation, option "character"
# Linter NestingDepth, option "ignore_parent_selectors"
# Linter PropertySortOrder, option "min_properties"
# Linter PropertySortOrder, option "separate_groups"
# Linter PropertySpelling, option "disabled_properties"
# Linter SpaceBeforeBrace, option "allow_single_line_padding"
# Linter VendorPrefix, option "identifier_list"

files:
  include: 'client/stylesheets/**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth:
    - 0
    - max-depth: 2
  border-zero:
    - 2
    - convention: zero
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
  clean-import-paths:
    - 2
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 2
    - style: long
  hex-notation:
    - 2
    - style: uppercase
  id-name-format:
    - 2
    - convention: hyphenatedlowercase
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: false
  mixin-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 2
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keywords: 2
  no-color-literals: 2
  no-css-comments: 1
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    - extra-properties: []
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 2
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes:
    - 1
    - additional-identifiers: []
      excluded-identifiers: []
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    - convention: hyphenatedlowercase
  property-sort-order:
    - 2
    - ignore-custom-properties: false
  property-units:
    - 2
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
      per-property: {}
  quotes:
    - 2
    - style: single
  shorthand-values:
    - 2
    - allowed-shorthands:
        - 2
        - 2
        - 3
        - 4
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon: 2
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property:
    - 0
    - properties: []
  variable-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 2

```
